name: Reflect Private Commits

on:
  schedule:
    - cron: '0 12 * * *'  # runs once per day at 12:00 UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Determine commit count
        id: commit_count
        run: |
          DAY=$(date +%-d) # day of the month (1–31)
          
          is_prime() {
            n=$1
            if [ "$n" -lt 2 ]; then
              return 1
            fi
            for ((i=2; i*i<=n; i++)); do
              if [ $((n % i)) -eq 0 ]; then
                return 1
              fi
            done
            return 0
          }

          COUNT=1
          if (( DAY % 2 == 0 )); then
            COUNT=2
          fi
          if is_prime $DAY; then
            COUNT=3
          fi

          echo "commits=$COUNT" >> $GITHUB_OUTPUT

      - name: Make commits
        run: |
          COUNT=${{ steps.commit_count.outputs.commits }}
          for i in $(seq 1 $COUNT); do
            # Generate a random hash (6 characters from SHA256)
            HASH=$(echo $RANDOM | sha256sum | cut -c1-6)
            
            # Append timestamp + hash to the log
            echo "$(date --utc +'%Y-%m-%dT%H:%M:%SZ') - $HASH" >> contributions.log
            
            # Commit changes
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git add contributions.log
            git commit -m "Automated commit $HASH"
          done
          git push
