name: Reflect Private Contributions

on:
  schedule:
    - cron: '0 12 * * *'  # runs once per day at 12:00 UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your public tracker repo
        uses: actions/checkout@v4
        with:
          repository: dlkritter/contributions
          token: ${{ secrets.CONTRIB_TOKEN }}  # personal access token with repo scope
          path: tracker

      - name: Determine commit count
        id: commit_count
        run: |
          DAY=$(date +%-d) # day of month (1–31)

          is_prime() {
            n=$1
            if [ "$n" -lt 2 ]; then return 1; fi
            for ((i=2; i*i<=n; i++)); do
              if [ $((n % i)) -eq 0 ]; then return 1; fi
            done
            return 0
          }

          COUNT=1
          if (( DAY % 2 == 0 )); then COUNT=2; fi
          if is_prime $DAY; then COUNT=3; fi

          echo "commits=$COUNT" >> $GITHUB_OUTPUT

      - name: Reflect Private Commit hashes
        run: |
          cd tracker
          COUNT=${{ steps.commit_count.outputs.commits }}
          for i in $(seq 1 $COUNT); do
            HASH=$(openssl rand -hex 3) # shorter, random 6-char hash
            echo "$(date --utc +'%Y-%m-%dT%H:%M:%SZ') - $HASH" >> contributions.log
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add contributions.log
            git commit -m "Automated commit $HASH"
          done
          git push
